
spring:

  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:tcp://localhost:9093/mem:testdb
    username: suhyuk0544
    password: suhyuk1027
    driver-class-name: org.h2.Driver
    generate-unique-name: false

#  mustache:
#    expose-session-attributes: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  logging:
    level:
      org.hibernate.SQL: debug

  sql:
    init:
      platform: h2

server:

  port: 8080

  ssl:
    enabled: true
    key-password: suhyuk1027
    key-store-password: suhyuk1027
    key-store: src/main/resources/ssl.jks

    key-store-type: "JKS"
    enabled-protocols:
    - TLSv1.1
    - TLSv1.2
    - TLSv1.3



  tomcat:

    #    connection-timeout: 20000

    remoteip:

      protocol-header:

  servlet:

    session:

      timeout: 60m

  #  main:
  #    web-application-type: none



