# curl -v -X POST "https://api.kakaobrain.com/v1/inference/kogpt/generation"
#    -H "Content-Type: application/json"
#    -H "Authorization: KakaoAK ${REST_API_KEY}"
#    -d '{
#        "prompt": "오늘 아침 하늘은 곧 비가 올 것 같아서",
#        "max_tokens": 120,
#        "n": 2
#        }'
POST https://api.kakaobrain.com/v1/inference/kogpt/generation
Content-Type: application/json

{
        "prompt": "정보:거주지 부산, 나이 20대, 성별 남자,  직업 기자, 말투 친절함 정보를 바탕으로 질문에 답하세요. Q:안녕하세요 반갑습니다. 자기소개 부탁드려도 될까요? A:",

        "max_tokens": 120
}

###

POST https://api.openai.com/v1/completions
Content-Type: application/json

{
  "max_tokens":120,
  "temperature":0.2,
  "model":"text-davinci-003",
  "prompt":"자바를 사용해서 너의 api 코드를 만들어줘"
}


###

POST https://localhost:8080/KakaoBot/school/detail
Content-Type: application/json

{
  "intent": {
    "id": "gmucdqb8c45fnpd0rr3krhdr",
    "name": "블록 이름"
  },
  "userRequest": {
    "timezone": "Asia/Seoul",
    "params": {
      "ignoreMe": "true"
    },
    "block": {
      "id": "gmucdqb8c45fnpd0rr3krhdr",
      "name": "블록 이름"
    },
    "utterance": "발화 내용",
    "lang": null,
    "user": {
      "id": "512368",
      "type": "accountId",
      "properties": {}
    }
  },
  "bot": {
    "id": "63ef45221727873452d80b45",
    "name": "봇 이름"
  },
  "action": {
    "name": "g7qd4wfygz",
    "clientExtra": null,
    "params": {
      "sys_constant": "양일고"
    },
    "id": "1vgk5w711t6l3sr6nixthi7c",
    "detailParams": {}
  }
}
###
POST https://localhost:8080/KakaoBot/school/detail
Content-Type: application/json

{
  "intent": {
    "id": "gmucdqb8c45fnpd0rr3krhdr",
    "name": "블록 이름"
  },
  "userRequest": {
    "timezone": "Asia/Seoul",
    "params": {
      "ignoreMe": "true"
    },
    "block": {
      "id": "gmucdqb8c45fnpd0rr3krhdr",
      "name": "블록 이름"
    },
    "utterance": "발화 내용",
    "lang": null,
    "user": {
      "id": "512368",
      "type": "accountId",
      "properties": {}
    }
  },
  "bot": {
    "id": "63ef45221727873452d80b45",
    "name": "봇 이름"
  },
  "action": {
    "name": "g7qd4wfygz",
    "params": {
      "sys_constant": "양일고"
    },
    "clientExtra":{
      "ORG_RDNDA": "(양서면/양서고등학교)",
      "FOND_SC_NM": "사립",
      "SPCLY_PURPS_HS_ORD_NM": null,
      "LCTN_SC_NM": "경기도",
      "HS_GNRL_BUSNS_SC_NM": "전문계",
      "ORG_RDNZC": "12584 ",
      "FOND_YMD": "19791121",
      "ATPT_OFCDC_SC_CODE": "J10",
      "ENG_SCHUL_NM": "Yangseo High School",
      "SD_SCHUL_CODE": "7530588",
      "HS_SC_NM": "일반고",
      "FOAS_MEMRD": "19791121",
      "SCHUL_NM": "양서고등학교",
      "LOAD_DTM": "20230615      ",
      "ATPT_OFCDC_SC_NM": "경기도교육청",
      "SCHUL_KND_SC_NM": "고등학교",
      "ENE_BFE_SEHF_SC_NM": "전기",
      "ORG_RDNMA": "경기도 양평군 양서면 상촌길 31-12",
      "ORG_FAXNO": "031-771-1418",
      "INDST_SPECL_CCCCL_EXST_YN": "N",
      "ORG_TELNO": "031-770-1400",
      "DGHT_SC_NM": "주간",
      "HMPG_ADRES": "www.yangseo.hs.kr",
      "JU_ORG_NM": "경기도교육청",
      "COEDU_SC_NM": "남여공학"
    },
    "id": "1vgk5w711t6l3sr6nixthi7c",
    "detailParams": {}
  }
}
###

POST https://localhost:8080/KakaoBot/info/me
Content-Type: application/json

{
  "intent": {
    "id": "gmucdqb8c45fnpd0rr3krhdr",
    "name": "블록 이름"
  },
  "userRequest": {
    "timezone": "Asia/Seoul",
    "params": {
      "ignoreMe": "true"
    },
    "block": {
      "id": "gmucdqb8c45fnpd0rr3krhdr",
      "name": "블록 이름"
    },
    "utterance": "발화 내용",
    "lang": null,
    "user": {
      "id": "512368",
      "type": "accountId",
      "properties": {}
    }
  },
  "bot": {
    "id": "63ef45221727873452d80b45",
    "name": "봇 이름"
  },
  "action": {
    "name": "g7qd4wfygz",
    "params": {
      "sys_constant": "양일고"
    },
    "clientExtra":{
      "ATPT_OFCDC_SC_NM":"경기도교육청",
      "ORG_RDNDA":"(양평읍)",
      "SCHUL_KND_SC_NM":"고등학교",
      "FOND_SC_NM":"공립",
      "ENE_BFE_SEHF_SA":"경기도 양평군 양평읍 양근로 260",
      "SD_SCHUL_CODE":"7530581",
      "ORG_FAXNO":"031-771-0434",
      "LCTN_SC_NM":"경기도",
      "HS_GNRL_BUSNS_SC_NM":"전문계",
      "INDST_SPECL_CCCCL_EXST_YN":"N",
      "FOND_YMD":"19470624",
      "ORG_RDNZC":"12562 ",
      "DGHT_SC_NM":"주간",
      "ORG_TELNO":"031-772-2580",
      "ATPT_OFCDC_SC_CODE":"J10",
      "ENG_SCHUL_NM":"Yangpyeong High School",
      "HS_SC_NM":"일반고",
      "FOAS_MEMRD":"19470624",
      "JU_ORG_NM":"경기도교육청",
      "SCHUL_NM":"양평고등학교",
      "LOAD_DTM":"20230326",
      "COEDU_SC_NM":"남여공학"
    },
    "id": "1vgk5w711t6l3sr6nixthi7c",
    "detailParams": {}
  }
}

###

POST https://www.suhyuk0544.xyz/KakaoBot/school
Content-Type: application/json

{
  "intent": {
    "id": "gmucdqb8c45fnpd0rr3krhdr",
    "name": "블록 이름"
  },
  "userRequest": {
    "timezone": "Asia/Seoul",
    "params": {
      "ignoreMe": "true"
    },
    "block": {
      "id": "gmucdqb8c45fnpd0rr3krhdr",
      "name": "블록 이름"
    },
    "utterance": "발화 내용",
    "lang": null,
    "user": {
      "id": "512368",
      "type": "accountId",
      "properties": {}
    }
  },
  "bot": {
    "id": "63ef45221727873452d80b45",
    "name": "봇 이름"
  },
  "action": {
    "name": "g7qd4wfygz",
    "clientExtra": null,
    "params": {
      "sys_constant": "양서고"
    },
    "id": "1vgk5w711t6l3sr6nixthi7c",
    "detailParams": {}
  }
}

###

POST https://localhost:8080/KakaoBot/diet
Content-Type: application/json

{
  "intent": {
    "id": "gmucdqb8c45fnpd0rr3krhdr",
    "name": "블록 이름"
  },
  "userRequest": {
    "timezone": "Asia/Seoul",
    "params": {
      "ignoreMe": "true"
    },
    "block": {
      "id": "gmucdqb8c45fnpd0rr3krhdr",
      "name": "블록 이름"
    },
    "utterance": "발화 내용",
    "lang": null,
    "user": {
      "id": "512368",
      "type": "accountId",
      "properties": {}
    }
  },
  "bot": {
    "id": "63ef45221727873452d80b45",
    "name": "봇 이름"
  },
  "action": {
    "name": "g7qd4wfygz",
    "clientExtra": null,
    "params": {
      "sys_constant": "양서고",
      "sys_date": "오늘"
    },
    "id": "1vgk5w711t6l3sr6nixthi7c",
    "detailParams": {
      "sys_date": {
        "value":"sys.date",
        "groupName":"",
        "origin":""
      }
    }
  }
}
